# Generated by Django 4.2.7 on 2023-12-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='publications_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='кол-во публикаций'),
        ),
    ]
