# Generated by Django 4.2.8 on 2023-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_alter_publication_views_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='publications_count',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='is_free',
        ),
        migrations.AlterField(
            model_name='channel',
            name='made_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
