# Generated by Django 4.2.8 on 2023-12-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_remove_channel_publications_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='link',
        ),
        migrations.AddField(
            model_name='payment',
            name='session_id',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='номер операции'),
        ),
        migrations.AddField(
            model_name='payment',
            name='success',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=200, null=True, verbose_name='сумма оплаты'),
        ),
    ]
