# Generated by Django 4.2.8 on 2023-12-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_remove_payment_channel_remove_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='made_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
    ]
