# Generated by Django 4.2.8 on 2023-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_alter_channel_made_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='бесплатный контент'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='content',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='made_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
